/**
 * Bindings come from WorkerEnv in worker-configuration.d.ts, generated by
 * `wrangler types` from wrangler.jsonc and .dev.vars -- so adding a binding
 * there is what makes it exist here, rather than a hand-kept duplicate list.
 *
 * Two adjustments the generator cannot make on its own: vars declared empty in
 * wrangler.jsonc are typed as the literal "", which is widened back to string;
 * and the secrets that are genuinely optional are marked optional, because a
 * deployment without TikTok credentials is a supported state that the pipeline
 * reports as "not configured".
 */
type Widen<T> = { [K in keyof T]: T[K] extends string ? string : T[K] };

/** Secrets a deployment can legitimately be missing. */
type OptionalSecret =
  | 'TIKTOK_CLIENT_KEY'
  | 'TIKTOK_CLIENT_SECRET'
  | 'TIKTOK_REDIRECT_URI'
  | 'TIKTOK_BUSINESS_CLIENT_ID'
  | 'TIKTOK_BUSINESS_CLIENT_SECRET'
  | 'TIKTOK_BUSINESS_AUTH_URL'
  | 'TIKTOK_BUSINESS_REDIRECT_URI';

export type Env = Widen<Omit<WorkerEnv, OptionalSecret>> &
  Partial<Pick<Widen<WorkerEnv>, OptionalSecret>>;

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export interface Automation {
  id: string;
  handler_key: string;
  name: string;
  description: string | null;
  app_id: string | null;
  cron: string | null;
  enabled: boolean;
  status: 'idle' | 'running' | 'failed' | 'disabled';
  config: Record<string, unknown>;
  next_run_at: string | null;
  last_run_at: string | null;
  running_since: string | null;
  failure_streak: number;
  icon: string;
  accent: string | null;
  kind: 'app' | 'system';
  orbit_ring: number;
  orbit_position: number | null;
  current_task: string | null;
}

export interface TikTokAccount {
  id: string;
  handle: string;
  display_name: string | null;
  app_id: string | null;
  open_id: string | null;
  access_token_enc: string | null;
  refresh_token_enc: string | null;
  token_expires_at: string | null;
  status: 'connected' | 'expired' | 'revoked' | 'error';
  daily_post_limit: number;
}

export interface Artifact {
  id: string;
  run_id: string | null;
  app_id: string | null;
  account_id: string | null;
  status: 'draft' | 'approved' | 'publishing' | 'published' | 'rejected' | 'failed';
  hook: string | null;
  caption: string | null;
  hashtags: string[];
  media_type: 'video' | 'photo';
  video_url: string | null;
  photo_urls: string[];
  asset_manifest: Record<string, unknown>;
  thumbnail_url: string | null;
  duration_s: number | null;
  publish_id: string | null;
  tiktok_post_id: string | null;
  error: string | null;
  scheduled_for: string | null;
  stage: string;
  stages: Record<string, { state: string; at?: string; note?: string }>;
  shot_notes: string | null;
  script: string | null;
  tiktok_privacy_level: TikTokPrivacyLevel | null;
  disable_comment: boolean;
  auto_add_music: boolean;
  brand_organic_toggle: boolean;
  brand_content_toggle: boolean;
  is_aigc: boolean;
  posting_consent_at: string | null;
}

export type TikTokPrivacyLevel =
  | 'PUBLIC_TO_EVERYONE'
  | 'FOLLOWER_OF_CREATOR'
  | 'MUTUAL_FOLLOW_FRIENDS'
  | 'SELF_ONLY';
