import { afterEach, describe, expect, it, vi } from 'vitest';
import { createExecutionContext, waitOnExecutionContext } from 'cloudflare:test';
import worker from '../src/index';
import { NATIVE_IMPORT_RENDERER, jpegDimensions } from '../src/lib/native-post-import';
import { authRoute, stubFetch, jsonResponse, testEnv, OWNER_TOKEN, OTHER_TOKEN } from './helpers';
import type { Artifact } from '../src/types';
import { produceArtifact } from '../src/automations/tiktok-produce';
import { Db } from '../src/lib/db';
const id='c536aa93-47e5-444b-aab8-e576a43d66ec';
const jpeg=(width=1080,height=1920)=>new Uint8Array([255,216,255,192,0,17,8,height>>8,height&255,width>>8,width&255,3,1,17,0,2,17,0,3,17,0,255,217]);
function pack(app:'cast'|'deadset'='cast') { return {version:1,id,app_slug:app,hook:'5 details worth saving',caption:'Save the context with your catch.',hashtags:['fishing'],promotional:true,feature_key:app==='deadset'?'workout_plan':undefined,reference_urls:['https://www.tiktok.com/@r1pple8'],slides:Array.from({length:app==='cast'?6:2},(_,i)=>({file:`slide-${String(i+1).padStart(2,'0')}.jpg`,role:i===0?'hook':app==='cast'?'editorial':'feature',overlay:i===0?'5 details worth saving':`Detail ${i}`,body:'Keep a useful note.',source:{kind:app==='deadset'&&i===1?'first_party_ui':'licensed_photo',source_url:`https://example.test/source-${i}`,creator:'Source owner',licence_url:'https://www.pexels.com/license/'}}))}; }
function request(p=pack(),token=OWNER_TOKEN,wrongSize=false,reverse=false){const form=new FormData();form.set('post',JSON.stringify(p));for(const s of reverse?[...p.slides].reverse():p.slides)form.append('slides',new File([jpeg(wrongSize?540:1080)],s.file,{type:'image/jpeg'}));return new Request('https://example.test/api/artifacts/import-native',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});}
async function call(req:Request){const ctx=createExecutionContext();const res=await worker.fetch(req,testEnv,ctx);await waitOnExecutionContext(ctx);return res;}
afterEach(()=>vi.unstubAllGlobals());
function backend(existing:Record<string,unknown>|null=null){let inserted:Record<string,unknown>|null=null;const trace=stubFetch([authRoute,{match:/\/rest\/v1\/artifacts/,respond:c=>{if(c.method==='POST'){inserted=c.body as Record<string,unknown>;return jsonResponse([inserted]);}return jsonResponse(existing?[existing]:[]);}},{match:/\/rest\/v1\/apps/,respond:()=>jsonResponse([{id:'app-id'}])},{match:/\/rest\/v1\/tiktok_accounts/,respond:()=>jsonResponse([{id:'account-id'}])},{match:/\/storage\/v1\/object\//,respond:()=>jsonResponse({})}]);return {trace,get inserted(){return inserted;}};}
describe('native post import',()=>{
 it('rejects non-owner uploads before storing anything',async()=>{const b=backend();expect((await call(request(pack(),OTHER_TOKEN))).status).toBe(401);expect(b.trace.calls).toHaveLength(1);});
 it('imports six ordered Cast slides with sources and retains every release hold',async()=>{const b=backend();const res=await call(request());expect(res.status).toBe(201);const row=await res.json() as Artifact;expect(row.status).toBe('draft');expect(row.account_id).toBe('account-id');expect(row.photo_urls).toHaveLength(6);expect(row.asset_manifest.requires_owner_review).toBe(true);expect(row.asset_manifest.visual_review).toBeUndefined();expect(row.asset_manifest.native_visual_review).toBeUndefined();expect(row.asset_manifest.production).toMatchObject({renderer:NATIVE_IMPORT_RENDERER,dimensions:{width:1080,height:1920}});const sources=(row.asset_manifest.production as {per_slide_sources:Array<{source_url:string;photo_url:string;sha256:string}>}).per_slide_sources;sources.forEach((s,i)=>{expect(s.source_url).toBe(`https://example.test/source-${i}`);expect(s.photo_url).toBe(row.photo_urls[i]);expect(s.sha256).toMatch(/^[a-f0-9]{64}$/);});expect(b.trace.calls.filter(c=>c.url.includes('/storage/')&&c.method==='POST')).toHaveLength(6);});
 it('imports Deadset app evidence without calling it stock or granting approval',async()=>{backend();const res=await call(request(pack('deadset')));expect(res.status).toBe(201);const row=await res.json() as Artifact;expect(row.photo_urls).toHaveLength(2);expect(row.asset_manifest.production).toMatchObject({per_slide_sources:[{kind:'licensed_photo'},{kind:'first_party_ui'}]});expect(row.asset_manifest.hook_visual_template).toMatchObject({id:'deadset-candid-person-v3'});});
 it('rejects wrong slide counts, file order and dimensions before uploads',async()=>{for(const req of [request({...pack(),slides:pack().slides.slice(0,2)}),request(pack(),OWNER_TOKEN,false,true),request(pack(),OWNER_TOKEN,true)]){const b=backend();expect((await call(req)).status).toBe(400);expect(b.trace.calls.some(c=>c.url.includes('/storage/'))).toBe(false);}});
 it('makes retrying an identical package idempotent and rejects changed content under the same id',async()=>{backend();const first=await call(request());const row=await first.json() as Record<string,unknown>;const b=backend(row);expect((await call(request())).status).toBe(200);expect(b.trace.calls.some(c=>c.method==='POST')).toBe(false);expect((await call(request({...pack(),caption:'Changed caption.'}))).status).toBe(409);});
 it('does not allow import metadata to inject an approval or another app',async()=>{backend();expect((await call(request({...pack(),status:'approved'} as ReturnType<typeof pack>))).status).toBe(400);expect((await call(request({...pack(),app_slug:'lifescore'} as unknown as ReturnType<typeof pack>))).status).toBe(400);});
 it('preserves imported pixels during later production',async()=>{const artifact={asset_manifest:{production:{renderer:NATIVE_IMPORT_RENDERER}}} as unknown as Artifact;expect(await produceArtifact(testEnv,new Db(testEnv),artifact,'cast')).toMatchObject({state:'blocked'});});
 it('reads JPEG dimensions and rejects invalid headers',()=>{expect(jpegDimensions(jpeg())).toEqual({width:1080,height:1920});expect(jpegDimensions(new Uint8Array([1,2,3]))).toBeNull();});
});
