/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.hq.jsonc --env-file=.hq.vars.example --include-runtime=false --env-interface=HqEnv hq-configuration.d.ts` (hash: 976e08a16bace4635c1fa195aeab00cd)
interface __BaseEnv_HqEnv {
	BASELINE: KVNamespace;
	ASSETS: Fetcher;
	DEADSET_SOURCE_URL: "https://fqfdygbveeztgxwkbmfi.supabase.co";
	DEADSET_SOURCE_KEY: string;
	AUTOMATIONS: Fetcher /* automations */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/hq");
	}
	interface Env extends __BaseEnv_HqEnv {}
}
interface HqEnv extends __BaseEnv_HqEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEADSET_SOURCE_URL" | "DEADSET_SOURCE_KEY">> {}
}
