import { useEffect, useState, type FormEvent } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import type { Session } from '@supabase/supabase-js';
import { api, supabase } from './lib/supabase';
import { useData } from './lib/useData';
import { LiveSyncProvider } from './lib/liveSync';
import type { Automation, Run } from './lib/types';
import type { DeadsetBaseline } from '../../worker/src/lib/deadset-baseline';
import Queue from './pages/Queue';
import './deadset-brand.css';

const paths: Record<string, string> = { home: 'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z', chart: 'M3 20h18 M6 16v-5 M12 16V4 M18 16V8', users: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M13 4a4 4 0 0 1 0 8 M20 21v-2a4 4 0 0 0-3-4 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8', play: 'm9 5 11 7-11 7z M3 5v14', coin: 'M12 2v20 M17 5H9a4 4 0 0 0 0 8h6a3 3 0 0 1 0 6H6', bolt: 'm13 2-9 12h7l-1 8 10-13h-8z', refresh: 'M20 7v5h-5 M4 17v-5h5 M5 8a8 8 0 0 1 14-2l1 3 M19 16A8 8 0 0 1 5 18l-1-3', arrow: 'M5 12h14 M13 6l6 6-6 6', logout: 'M9 4H4v16h5 M9 12h12 M16 7l5 5-5 5', shield: 'm12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z M8 12l3 3 5-6', data: 'M3 6c0-4 18-4 18 0s-18 4-18 0v12c0 4 18 4 18 0V6 M3 12c0 4 18 4 18 0' };
function Glyph({ name, className = '' }: { name: string; className?: string }) { return <svg className={className} width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name] ?? paths.chart} /></svg>; }
const navigation = [{ to: '/deadset', label: 'Overview', icon: 'home' }, { to: '/acquisition', label: 'Acquisition', icon: 'users' }, { to: '/revenue', label: 'Revenue', icon: 'coin' }, { to: '/content', label: 'Content studio', icon: 'play' }, { to: '/automations', label: 'Automations', icon: 'bolt' }, { to: '/sources', label: 'Data sources', icon: 'data' }];
function Wordmark() { return <span className="ds-wordmark">DEAD<span>SET</span><small>HQ</small></span>; }
function OwnerLogin() {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function signIn(e: FormEvent) {
    e.preventDefault(); setBusy(true); setError('');
    try { const result = await supabase.auth.signInWithPassword({ email, password }); if (result.error) throw result.error; }
    catch (err) { setError(err instanceof Error ? err.message : 'Sign-in failed. Please try again.'); }
    finally { setBusy(false); }
  }
  return <div className="ds-login"><div className="ds-login-art"><Wordmark /><div><p className="ds-kicker">BUILT FOR THE LONG GAME</p><h1>EVERY REP.<br />EVERY USER.<br /><em>EVERY STEP.</em></h1><p>The home of DEADSET growth.</p></div><small>FORGE YOUR BODY. BUILD YOUR BUSINESS.</small></div><section className="ds-login-form"><div className="ds-lock"><Glyph name="shield" /></div><p className="ds-kicker">OWNER ACCESS</p><h2>Back to work.</h2><p>Your numbers. Your next move.</p><form onSubmit={signIn}><label>Email address<input type="email" autoComplete="username" required value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} /></label><button className="ds-primary" disabled={busy}>{busy ? 'Signing in…' : 'Enter DEADSET HQ'}<Glyph name="arrow" /></button>{error && <p className="ds-alert" role="alert">{error}</p>}</form><small>Use your existing automation dashboard owner account.</small></section></div>;
}
async function loadDashboard() {
  const baselineRequest = api<{ current: DeadsetBaseline | null; previous: DeadsetBaseline | null }>('/deadset/baselines').then(result => ({ ...result, error: null as string | null })).catch(error => ({ current: null, previous: null, error: error instanceof Error ? error.message : 'Baseline unavailable' }));
  const app = await supabase.from('apps').select('id').eq('slug', 'deadset').single();
  if (app.error) { await baselineRequest; throw app.error; }
  const id = app.data.id;
  const [agents, accounts, drafts, posted, baseline] = await Promise.all([
    supabase.from('automations').select('*').eq('app_id', id).order('name'),
    supabase.from('tiktok_accounts_public').select('id,handle,status').eq('app_id', id),
    supabase.from('artifacts').select('id', { count: 'exact', head: true }).eq('app_id', id).eq('status', 'draft'),
    supabase.from('artifacts').select('id', { count: 'exact', head: true }).eq('app_id', id).eq('status', 'published').gte('published_at', new Date(Date.now() - 7 * 86400000).toISOString()), baselineRequest,
  ]);
  for (const result of [agents, accounts, drafts, posted]) if (result.error) throw result.error;
  const automations = agents.data as Automation[];
  const [channels, runs] = await Promise.all([
    Promise.all((accounts.data ?? []).map(async account => {
      const result = await supabase.from('analytics_snapshots').select('captured_at,views_28d,followers,shares_28d,quality').eq('account_id', account.id).order('captured_at', { ascending: false }).limit(1).maybeSingle();
      if (result.error) throw result.error;
      return { ...account, snapshot: result.data };
    })),
    automations.length ? supabase.from('runs').select('*').in('automation_id', automations.map(a => a.id)).order('started_at', { ascending: false }).limit(12) : Promise.resolve({ data: [], error: null }),
  ]);
  if (runs.error) throw runs.error;
  return { baseline: baseline.current, previous: baseline.previous, baselineError: baseline.error, automations, channels, runs: runs.data as Run[], drafts: drafts.count, posted: posted.count };
}
function Metric({ label, value, note, icon, red = false }: { label: string; value: number | null | undefined; note: string; icon: string; red?: boolean }) {
  return <article className={`ds-metric ${red ? 'ds-metric-red' : ''}`}><div><span>{label}</span><Glyph name={icon} /></div><strong>{value == null ? '—' : value.toLocaleString()}</strong><small>{note}</small></article>;
}
function Dashboard({ session }: { session: Session }) {
  const location = useLocation();
  const { data, error, refresh, loading } = useData(loadDashboard, [], 60000);
  const [busy, setBusy] = useState(''), [notice, setNotice] = useState('');
  const page = navigation.find(item => item.to === location.pathname) ?? navigation[0]!;
  const b = data?.baseline;
  async function refreshSource() {
    setBusy('refresh'); setNotice('');
    try { await api('/deadset/refresh', { method: 'POST' }); refresh(); setNotice('Data refreshed. Recent snapshots may be reused for five minutes.'); }
    catch (err) { setNotice(err instanceof Error ? err.message : 'Refresh failed'); }
    finally { setBusy(''); }
  }
  async function toggle(a: Automation) {
    setBusy(a.id); setNotice('');
    try { await api(`/automations/${a.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: !a.enabled }) }); refresh(); setNotice(`${a.name} ${a.enabled ? 'paused' : 'resumed'}.`); }
    catch (err) { setNotice(err instanceof Error ? err.message : 'Update failed'); }
    finally { setBusy(''); }
  }
  const sourcePanel = <section className="ds-panel"><div className="ds-section-title"><div><p className="ds-kicker">ATTRIBUTION</p><h2>Where it starts.</h2></div><span className="ds-tag">All-time profiles</span></div>{b ? <div className="ds-sources"><div className="ds-donut" style={{ background: `conic-gradient(#e63222 0 ${(b.sources.filter(s => s.source !== 'unattributed').reduce((n, s) => n + s.users, 0) / (b.registered_users || 1)) * 100}%, #303030 0 100%)` }}><div><strong>{b.registered_users}</strong><small>PROFILES</small></div></div><div className="ds-source-list">{b.sources.map(source => <div key={source.source}><span><i className={source.source === 'unattributed' ? 'unknown' : ''} />{source.source}</span><strong>{source.users}</strong><small>{b.registered_users ? Math.round(source.users / b.registered_users * 100) : 0}%</small></div>)}</div></div> : <p className="ds-empty">Source attribution appears after the first successful sync.</p>}<p className="ds-footnote">Direct means no recognised campaign was stored. This does not establish which post caused an install.</p></section>;
  const funnel = <section className="ds-panel"><div className="ds-section-title"><div><p className="ds-kicker">ACTIVATION</p><h2>Make the second workout happen.</h2></div><Glyph name="chart" /></div><div className="ds-funnel">{[['Registered profiles', b?.registered_users], ['Synced profiles', b?.synced_users], ['First workout', b?.first_workout_users], ['Second workout', b?.second_workout_users]].map(([label, count], index) => <div className="ds-funnel-row" key={label}><div><span><small>0{index + 1}</small>{label}</span><strong>{count ?? '—'}</strong></div><div className="ds-track"><i style={{ width: `${typeof count === 'number' && b?.registered_users ? count / b.registered_users * 100 : 0}%`, animationDelay: `${index * 90}ms` }} /></div></div>)}</div><p className="ds-footnote">Observed all-time synced records. These are not mature-cohort conversion rates.</p></section>;
  const sourceStatus = <section className="ds-panel"><div className="ds-section-title"><div><p className="ds-kicker">MEASUREMENT COVERAGE</p><h2>Clarity before scale.</h2></div><Glyph name="shield" /></div><div className="ds-integrations">{[['Product database', b ? 'Connected' : 'Awaiting sync', 'Registered profiles and synced workouts'], ['Stripe records', b ? 'Connected' : 'Awaiting sync', 'Live subscriptions; no verified price ledger'], ['TikTok', data?.channels.some(c => c.snapshot) ? 'Connected' : 'Awaiting sync', 'Account and sampled-post lifetime metrics'], ['RevenueCat', 'Not connected', 'iOS subscribers, renewals and refunds'], ['App Store Connect', 'Not connected', 'Downloads and listing conversion'], ['Retention events', 'Not connected', 'First opens and mature D1 / D7 / D30 cohorts']].map(([name, status, detail]) => <article key={name}><div><strong>{name}</strong><small>{detail}</small></div><span className={`ds-tag ${status === 'Connected' ? 'ds-tag-green' : ''}`}>{status}</span></article>)}</div></section>;
  const automations = <section className="ds-panel"><div className="ds-section-title"><div><p className="ds-kicker">THE ENGINE ROOM</p><h2>Keep things moving.</h2></div><span className="ds-tag">DEADSET only</span></div>{data?.automations.map(a => <article className="ds-agent" key={a.id}><span className={`ds-agent-icon ${a.enabled ? 'active' : ''}`}><Glyph name="bolt" /></span><div><strong>{a.name}</strong><small>{a.enabled ? a.status : 'Paused'}{a.failure_streak ? ` · ${a.failure_streak} consecutive failures` : ''}</small></div><button disabled={Boolean(busy)} onClick={() => toggle(a)}>{busy === a.id ? 'Saving…' : a.enabled ? 'Pause' : 'Resume'}</button></article>)}{data?.automations.length === 0 && <p className="ds-empty">No DEADSET-specific automations configured.</p>}<a className="ds-text-link" href="https://automations.theojandhyala.workers.dev" target="_blank" rel="noreferrer">Open shared publishing controls <Glyph name="arrow" /></a></section>;
  return <div className="ds-app"><aside className="ds-sidebar"><Link to="/deadset" aria-label="DEADSET HQ overview"><Wordmark /></Link><p className="ds-side-label">YOUR OPERATING SYSTEM</p><nav aria-label="Main navigation">{navigation.map(item => <NavLink className={({ isActive }) => isActive || (item.to === '/deadset' && location.pathname === '/') ? 'active' : ''} to={item.to} key={item.to}><Glyph name={item.icon} />{item.label}<span>↗</span></NavLink>)}</nav><div className="ds-focus"><span className="ds-kicker">ONE APP. ALL IN.</span><strong>THE NEXT<br /><em>100.</em></strong><p>Retained paying users.<br />The first milestone.</p><div className="ds-focus-line" /></div><div className="ds-owner"><span className="ds-avatar">T</span><div><strong>Owner workspace</strong><small>Private access</small></div><button title={`Sign out ${session.user.email ?? ''}`} aria-label="Sign out" onClick={() => supabase.auth.signOut()}><Glyph name="logout" /></button></div></aside><div className="ds-workspace"><header className="ds-topbar"><span>Workspace <b>/</b> <strong>{page.label}</strong></span><div><span className="ds-private"><Glyph name="shield" /> Private</span><span className="ds-top-date">{new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</span></div></header><main key={location.pathname} className="ds-main"><div className="ds-page-head"><div><p className="ds-kicker">DEADSET / {page.label.toUpperCase()}</p><h1>{page.label === 'Overview' ? <>GROW WITH <em>INTENT.</em></> : page.label === 'Acquisition' ? <>EVERY USER HAS <em>A START.</em></> : page.label === 'Revenue' ? <>BUILD SOMETHING <em>THAT LASTS.</em></> : page.label === 'Content studio' ? <>CREATE. TEST. <em>LEARN.</em></> : page.label === 'Automations' ? <>LESS REPETITION.<br /><em>MORE PROGRESS.</em></> : <>TRUST <em>THE NUMBERS.</em></>}</h1><p>{page.label === 'Overview' ? 'Your product, your people, your next move.' : 'A focused view of the work that moves DEADSET forward.'}</p></div><button className="ds-refresh" onClick={refreshSource} disabled={Boolean(busy)}><Glyph name="refresh" className={busy === 'refresh' ? 'ds-spin' : ''} />{busy === 'refresh' ? 'Refreshing…' : 'Refresh data'}</button></div>
      {(error || data?.baselineError) && <p className="ds-alert" role="alert">{error || data?.baselineError} Previous snapshots remain available when a refresh fails.</p>}{notice && <p className="ds-notice" role="status">{notice}</p>}
      <div className="ds-data-stamp"><span className={`ds-status-dot ${b ? '' : 'pending'}`} /><span>{b ? `Product snapshot · ${new Date(b.captured_at).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })} · refreshes hourly` : loading ? 'Connecting to your data…' : 'Waiting for a product snapshot'}</span>{b && Date.now() - Date.parse(b.captured_at) > 2 * 3600000 && <span className="ds-stale">Delayed</span>}<span className="ds-period">Activity: rolling 7 days</span></div>
      {['Overview', 'Acquisition'].includes(page.label) && <><div className="ds-kpis"><Metric label="Registered profiles" value={b?.registered_users} note={b ? `${b.signups_7d} new in the last 7 days` : 'Product database'} icon="users" red /><Metric label="Completed workouts" value={b?.workouts_7d} note="Last 7 days · synced records" icon="bolt" /><Metric label="Live Stripe subscribers" value={b?.stripe_active_subscribers} note="Stripe only · excludes iOS" icon="coin" /><Metric label="TikTok posts" value={data?.posted} note="Published in the last 7 days" icon="play" /></div><div className="ds-grid-two">{funnel}{sourcePanel}</div></>}
      {page.label === 'Overview' && <><div className="ds-attention"><span className="ds-attention-number">01</span><div><p className="ds-kicker">NEXT BEST MOVE</p><h3>{b?.orphan_state_records ? 'Close the gaps before scaling.' : 'Make activation measurable.'}</h3><p>{b ? `${b.orphan_state_records} saved states have no matching profile. Check sync coverage before making growth decisions.` : 'Connect product and subscription sources to establish a reliable baseline.'}</p></div><Link to="/sources" aria-label="Inspect data sources"><Glyph name="arrow" /></Link></div><div className="ds-grid-two">{automations}<section className="ds-panel"><div className="ds-section-title"><div><p className="ds-kicker">CONTENT LAB</p><h2>Attention is the start.</h2></div><Glyph name="play" /></div><div className="ds-content-total"><strong>{data?.drafts ?? '—'}</strong><div>drafts waiting<br /><span>for your review</span></div></div><p className="ds-footnote">Quality first. Approve the exact creative before it reaches your audience.</p><Link className="ds-primary" to="/content">Open content studio <Glyph name="arrow" /></Link></section></div></>}
      {page.label === 'Acquisition' && <section className="ds-panel"><p className="ds-kicker">THE FULL JOURNEY</p><h2>From first touch to habit.</h2><div className="ds-journey">{['Content', 'Store visit', 'Install', 'Account', 'Workout', 'Trial', 'Pro', 'Renewal'].map((s, i) => <span key={s}><small>0{i + 1}</small>{s}</span>)}</div><p className="ds-footnote">Store-to-install attribution, trial conversion and renewal cohorts still need connected sources. No inferred installs from views.</p></section>}
      {page.label === 'Revenue' && <><div className="ds-kpis"><Metric label="Live Stripe subscribers" value={b?.stripe_active_subscribers} note="Provider records · active paid time" icon="coin" red /><Metric label="Stripe trials" value={b?.stripe_trial_subscribers} note="Live environment only" icon="users" /><Metric label="Cancelling subscribers" value={b?.stripe_cancelling_subscribers} note="Still within paid time · Stripe only" icon="chart" /><Metric label="Monthly recurring revenue" value={null} note="Awaiting billing amounts and iOS feed" icon="coin" /></div>{sourceStatus}<p className="ds-footnote">No total MRR, churn or lifetime value is reported until provider coverage and billing amounts are verified.</p></>}
      {page.label === 'Content studio' && <><div className="ds-channel-grid">{data?.channels.map(c => <section className="ds-panel" key={c.id}><div className="ds-section-title"><h2>@{c.handle}</h2><span className={`ds-tag ${c.status === 'connected' ? 'ds-tag-green' : ''}`}>{c.status}</span></div><div className="ds-kpis ds-small-kpis"><Metric label="Followers" value={c.snapshot?.followers} note="Latest snapshot" icon="users" /><Metric label="Sampled lifetime views" value={c.snapshot?.views_28d} note="Recent posts · not weekly views" icon="play" /></div><p className="ds-footnote">{c.snapshot ? `${c.snapshot.quality} data · captured ${new Date(c.snapshot.captured_at).toLocaleString()}` : 'No analytics snapshot yet.'}</p></section>)}</div><div className="ds-legacy"><Queue appSlug="deadset" /></div></>}
      {page.label === 'Automations' && <>{automations}<section className="ds-panel"><div className="ds-section-title"><div><p className="ds-kicker">RUN HISTORY</p><h2>Nothing hidden.</h2></div><span className="ds-tag">Latest 12 runs</span></div>{data?.runs.map(run => <article className="ds-run" key={run.id}><span className={`ds-status-dot ${run.status === 'failed' ? 'failed' : run.status !== 'succeeded' ? 'pending' : ''}`} /><div><strong>{data.automations.find(a => a.id === run.automation_id)?.name ?? 'Automation'}</strong><small>{run.error ?? run.status}</small></div><time>{new Date(run.started_at).toLocaleString('en-GB', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</time></article>)}{data?.runs.length === 0 && <p className="ds-empty">No recorded runs yet.</p>}</section></>}
      {page.label === 'Data sources' && <>{sourceStatus}<section className="ds-panel"><p className="ds-kicker">DATA QUALITY</p><h2>What the snapshot leaves out.</h2><div className="ds-kpis"><Metric label="Unmatched saved states" value={b?.orphan_state_records} note="Excluded from profile activity" icon="data" /><Metric label="Invalid workout records" value={b?.invalid_workout_records} note="Excluded from workout counts" icon="shield" /><Metric label="Non-live subscriptions" value={b?.excluded_sandbox_subscriptions} note="Never counted as production revenue" icon="coin" /><Metric label="Unknown expiry" value={b?.stripe_unknown_expiry} note="Excluded until verified" icon="chart" /></div><p className="ds-footnote">Workouts describe synced activity, not foreground DAU/WAU. Counts can change as devices sync. Missing sources remain unknown.</p></section></>}
      <footer className="ds-footer"><span><b>DEADSET</b> HQ / BUILT FOR THE LONG GAME.</span><span>100 → 500 → 1,000 paying users → £10k MRR</span></footer></main></div></div>;
}
export default function DeadsetApp() {
  const [session, setSession] = useState<Session | null>(null), [ready, setReady] = useState(false);
  useEffect(() => { let mounted = true; supabase.auth.getSession().then(({ data }) => { if (mounted) { setSession(data.session); setReady(true); } }); const { data } = supabase.auth.onAuthStateChange((_event, s) => { setSession(s); setReady(true); }); return () => { mounted = false; data.subscription.unsubscribe(); }; }, []);
  useEffect(() => { document.title = 'DEADSET HQ — Growth, with intent'; document.documentElement.classList.add('deadset-site'); return () => document.documentElement.classList.remove('deadset-site'); }, []);
  if (!ready) return <div className="ds-boot"><Wordmark /><span>Opening your workspace…</span></div>;
  if (!session) return <OwnerLogin />;
  return <LiveSyncProvider><Dashboard session={session} /></LiveSyncProvider>;
}
